name: Sync fork
on:
  workflow_dispatch:

  schedule:
    - cron: "10 1 * * 1-5" # 09:10 a.m. China; Workday only


jobs:
  sync-fork:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
        - pacoxu/kubernetes
        - pacoxu/containerd
    steps:
    - name: Sync Fork
      uses: wzshiming/action-sync-fork@v1
      env:
        REPOSITORY: ${{ matrix.repo }}
        GH_TOKEN: ${{ secrets.GH_FORK_REPO_TOKEN }}
